server:
  port: 8000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    # To persist on disk:
    # url: jdbc:h2:./database/storage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /db
      settings:
        trace: false
        web-allow-others: true
  gson:
    date-format: "yyyy-MM-dd"
